server:
    port: 20040

logging:
    file:
        name: /log/202008/slacktohtml.log
    level:
        root: DEBUG
    

FILE_UPLOAD_PATH: D:/data/slacktohtml/tmp/

spring:
    servlet:
        multipart:
            location: D:/data/slacktohtml/tmp/