server:
    port: 20040

logging:
    file:
        name: /log/202008/slacktohtml.log
    level:
        root: DEBUG

spring:
    servlet:
        multipart:
            location: D:/data/slacktohtml/tmp/


# slack parse filename string list
slack:
    parse:
        filename: users.json, channels.json